using Microsoft.CodeAnalysis;

namespace OpenDictionary.CodeAnalysis.EnumToInterface.Generators;

[Generator]
public class AttributeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (context, source) =>
        {
            // Build up the source code
            string code = $$"""
            // <auto-generated/>

            #nullable enable
             
            namespace OpenDictionary.CodeAnalysis;

            public class {{Attributes.EnumToInterface.FullName}} : Attribute 
            {
                public string? {{Attributes.EnumToInterface.InterfaceName}} { get; set; }
            }
            """;

            // Add the source code to the compilation
            context.AddSource($"{Attributes.EnumToInterface.FullName}.g.cs", code);
        });
    }
}
